define(function() {
  var BASELINE_POSITIONS = {
    ABOVE_BASELINE: 'ABOVE_BASELINE',
    BELOW_BASELINE: 'BELOW_BASELINE',
    ON_BASELINE: 'ON_BASELINE',
    SENTENCE_CIRCLE: 'SENTENCE_CIRCLE'
  };

  var _letterBaselinePositions = {
    a: BASELINE_POSITIONS.BELOW_BASELINE,
    b: BASELINE_POSITIONS.ON_BASELINE,
    ch: BASELINE_POSITIONS.ON_BASELINE,
    d: BASELINE_POSITIONS.ON_BASELINE,
    e: BASELINE_POSITIONS.ON_BASELINE,
    f: BASELINE_POSITIONS.ON_BASELINE,
    g: BASELINE_POSITIONS.ON_BASELINE,
    h: BASELINE_POSITIONS.ON_BASELINE,
    i: BASELINE_POSITIONS.ON_BASELINE,
    j: BASELINE_POSITIONS.ABOVE_BASELINE,
    k: BASELINE_POSITIONS.ABOVE_BASELINE,
    l: BASELINE_POSITIONS.ABOVE_BASELINE,
    m: BASELINE_POSITIONS.ABOVE_BASELINE,
    n: BASELINE_POSITIONS.ABOVE_BASELINE,
    o: BASELINE_POSITIONS.ABOVE_BASELINE,
    p: BASELINE_POSITIONS.ABOVE_BASELINE,
    qu: BASELINE_POSITIONS.ON_BASELINE,
    r: BASELINE_POSITIONS.ON_BASELINE,
    sh: BASELINE_POSITIONS.ON_BASELINE,
    s: BASELINE_POSITIONS.ON_BASELINE,
    t: BASELINE_POSITIONS.ON_BASELINE,
    u: BASELINE_POSITIONS.ON_BASELINE,
    v: BASELINE_POSITIONS.ON_BASELINE,
    w: BASELINE_POSITIONS.ON_BASELINE,
    x: BASELINE_POSITIONS.ON_BASELINE,
    y: BASELINE_POSITIONS.ON_BASELINE,
    z: BASELINE_POSITIONS.ON_BASELINE,
    ng: BASELINE_POSITIONS.ON_BASELINE,
    th: BASELINE_POSITIONS.ON_BASELINE,
    '.': BASELINE_POSITIONS.SENTENCE_CIRCLE,
    '?': BASELINE_POSITIONS.SENTENCE_CIRCLE,
    '!': BASELINE_POSITIONS.SENTENCE_CIRCLE,
    '"': BASELINE_POSITIONS.SENTENCE_CIRCLE,
    '\'': BASELINE_POSITIONS.ON_BASELINE,
    '-': BASELINE_POSITIONS.SENTENCE_CIRCLE,
    ',': BASELINE_POSITIONS.SENTENCE_CIRCLE,
    '0': BASELINE_POSITIONS.ON_BASELINE,
    '1': BASELINE_POSITIONS.ON_BASELINE,
    '2': BASELINE_POSITIONS.ON_BASELINE,
    '3': BASELINE_POSITIONS.ON_BASELINE,
    '4': BASELINE_POSITIONS.ON_BASELINE,
    '5': BASELINE_POSITIONS.ABOVE_BASELINE,
    '6': BASELINE_POSITIONS.ABOVE_BASELINE,
    '7': BASELINE_POSITIONS.ABOVE_BASELINE,
    '8': BASELINE_POSITIONS.BELOW_BASELINE,
    '9': BASELINE_POSITIONS.BELOW_BASELINE
  };

  function getBaselinePosition(letter) {
    return _letterBaselinePositions[letter];
  };

  return {
    BASELINE_POSITIONS: BASELINE_POSITIONS,
    getBaselinePosition: getBaselinePosition
  };
});
